env:
  - name: CLIENT_ID
    value: "clientId"
  - name: CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        key: clientSecret
        name: kc-reporter
podLabels:
  a: "b"
podAnnotations:
  # see https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html
  co.elastic.logs/enabled: "true"
keycloak:
  config:
    url: http://localhost:8080
    webhookType: test
    webhookUrl: http://localhost:8888
