{{- $fullName := include "keycloak-reporter.fullname" . -}}
{{- range .Values.cronjobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-job-%s" $fullName .name }}
spec:
  schedule: "{{ .schedule }}"
  jobTemplate:
    spec:
      template:
        {{- with $.Values.podAnnotations }}
        annotations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        spec:
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          containers:
            - name: {{ .name }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              command:
                - /bin/sh
                - -c
                - {{ .script }}
              env:
                - name: CONFIG_FILE
                  value: "/app/config.json"
              volumeMounts:
                - name: config-file
                  mountPath: "/app/config.json"
                  readOnly: true
                - name: reports-dir
                  mountPath: "/app/reports"
          restartPolicy: OnFailure
          {{- if $.Values.resources }}
          resources:
            {{ toYaml $.Values.resources }}
          {{- end }}
          {{- if $.Values.nodeSelector }}
          nodeSelector:
            {{ toYaml $.Values.nodeSelector | indent 12 }}
          {{- end }}
          {{- if $.Values.tolerations }}
          tolerations:
            {{ toYaml $.Values.tolerations | indent 12 }}
          {{- end }}
          volumes:
          - name: config-file
            secret:
              secretName: {{ $fullName }}
          {{- if (.Values.keycloak.config.volumes).reports }}
          - name: reports-dir
            persistentVolumeClaim:
              claimName: {{ $fullName }}-reports
          {{- end }}
---
{{- end -}}
