{{- $fullName := include "keycloak-reporter.fullname" . }}
{{- range $name, $config := include "keycloak-reporter.cronJobs" $ | fromYaml }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-job-%s" $fullName $name }}
  annotations:
    {{- include "keycloak-reporter.annotations" $ | nindent 4 }}
  labels:
    {{- include "keycloak-reporter.labels" $ | nindent 4 }}
spec:
  schedule: {{ $config.schedule }}
  jobTemplate:
    spec:
      template:
        annotations:
          {{- include "keycloak-reporter.annotations" $ | nindent 8 }}
        labels:
          {{- include "keycloak-reporter.labels" $ | nindent 8 }}
        spec:
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ default "default" ($.Values.serviceAccount).name }}
          securityContext:
            {{- toYaml $.Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ $name }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              command:
                - node
                - /app/cli.js
                - {{ $config.script }}
              env:
                - name: CONFIG_FILE
                  value: "/app/config.json"
                {{- with $.Values.env }}
                {{- tpl (toYaml .) $  | nindent 16 }}
                {{- end }}
              {{- if $.Values.resources }}
              resources:
                {{- toYaml $.Values.resources | nindent 16 }}
              {{- end }}
              securityContext:
                {{- toYaml $.Values.securityContext | nindent 16 }}
              volumeMounts:
                - name: config-file
                  mountPath: "/app/config.json"
                  subPath: "config.json"
                  readOnly: true
                {{- if ($.Values.keycloak.config.volumes).reports }}
                - name: reports-dir
                  mountPath: "/app/reports"
                {{- end }}
          restartPolicy: OnFailure
          {{- if $.Values.nodeSelector }}
          nodeSelector:
            {{ toYaml $.Values.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if $.Values.tolerations }}
          tolerations:
            {{ toYaml $.Values.tolerations | nindent 12 }}
          {{- end }}
          volumes:
          - name: config-file
            secret:
              secretName: {{ $fullName }}
          {{- if ($.Values.keycloak.config.volumes).reports }}
          - name: reports-dir
            persistentVolumeClaim:
              claimName: {{ $fullName }}-reports
          {{- end }}
---
{{- end -}}