{{- $fullName := include "keycloak-reporter.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
data:
  {{- range $k, $v := .Values.keycloak.config }}
  {{ $k }}: {{ $v }}
  {{- end }}
  {{- if (.Values.keycloak.config.volumes).reports }}
  reports: /app/reports
  {{- end }}
