{{- $fullName := include "keycloak-reporter.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
data:
  {{- range $k, $v := .Values.keycloak.config }}
  - name: {{ $k }}
    value: {{ $v }}
  {{- end }}
