{{- $fullName := include "keycloak-reporter.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
stringData:
  config.json: |
    {{- $config:= .Values.keycloak.config }}
    {{- if (.Values.keycloak.config.volumes).reports }}
    $config := merge $config (dict "reports" "/app/reports")
    {{- end }}
    {{ $config | toJson  }}
